name: CI Terraform RDS

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform fmt -check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -var="environment=${{ github.ref_name }}"

      - name: Terraform Apply Dev
        if: github.ref_name == 'dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="environment=dev"

      - name: Terraform Apply Prod
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="environment=prod"