name: CI for Pull Request Approval

on:
  pull_request:
    branches:
      - dev
      - homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Run Terraform fmt
        run: terraform fmt
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Run Terraform init
        run: terraform init
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Run Terraform plan
        run: terraform plan
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Notify Success
        if: success()
        run: echo "All checks passed. Ready for approval."
