name: CI for Pull Request Approval  # Nome do workflow visível na aba de Actions do GitHub.

on:
  pull_request:
    branches:
      - dev
      - homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # O pipeline será executado em uma máquina virtual com o Ubuntu mais recente.

    steps:
      - name: Checkout repository  # Passo para clonar o código do repositório.
        uses: actions/checkout@v3

      - name: Setup Terraform  # Passo para configurar o Terraform no ambiente de CI.
        uses: hashicorp/setup-terraform@v2
        # Executa apenas se houver arquivos .tf no repositório
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Run Terraform fmt -check  # Passo que roda o comando para verificar a formatação do Terraform.
        run: terraform fmt -check  # Comando que verifica se a formatação dos arquivos .tf está correta.
        # Executa apenas se houver arquivos .tf no repositório
        if: "contains(github.event.pull_request.changed_files, '.tf')"

      - name: Notify Success  # Passo para notificar que os checks foram bem-sucedidos.
        if: success()  # Executa este passo apenas se o passo anterior (fmt check) passar.
        run: echo "All checks passed. Ready for approval."