name: CI for Pull Request Approval

on:
  pull_request:
    branches:
      - dev
      - homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform fmt -check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply for Dev
        if: github.event.pull_request.merged == true && github.base_ref == 'dev'
        run: terraform apply -auto-approve

      - name: Terraform Apply for Prod
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        run: terraform apply -auto-approve

      - name: Notify Success
        if: success()
        run: echo "All checks passed. Ready for approval."