name: Terraform merge prod

on:
  push:
    branches:
      - main

jobs:
  terraform-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pull-requests: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
      TF_VAR_db_name: ${{ secrets.DB_NAME_PROD }}
      TF_VAR_allocated_storage: ${{ vars.ALLOCATED_STORAGE_PROD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform State
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate.d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false

      - name: Upload Terraform State
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate.d