name: Terraform

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform-checks:
    name: 'Terraform PR Checks'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.base_ref == 'dev' || github.base_ref == 'main')
    permissions:
      pull-requests: write

    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
      TF_VAR_environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan

  terraform-dev:
    name: 'RDS in dev'
    runs-on: ubuntu-latest
    needs: terraform-checks
    if: github.ref == 'refs/heads/dev'
    permissions:
      pull-requests: write

    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
      TF_VAR_environment: 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false

  terraform-main:
    name: 'RDS in main'
    runs-on: ubuntu-latest
    needs: [ terraform-dev, terraform-checks ]
    if: github.ref == 'refs/heads/main'
    permissions:
      pull-requests: write

    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
      TF_VAR_environment: 'prod'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false