name: Terraform merge dev

on:
  push:
    branches:
      - dev

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    permissions:
      pull-requests: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
      TF_VAR_environment: 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false