name: Terraform Merge

on:
  push:
    branches:
      - main

jobs:
  terraform-main:
    name: 'create RDS prod'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pull-requests: write

    env:
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
      TF_VAR_environment: 'prod'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false