name: Terraform CI/CD

on:
  pull_request:
    branches:
      - dev
      - main

  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
          TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

      - name: Terraform Apply on Merge (dev)
        if: github.ref == 'refs/heads/dev' && success()
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_environment: dev
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}

      - name: Terraform Apply on Merge (production)
        if: github.ref == 'refs/heads/main' && success()
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_environment: prod
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}

      - name: Fail if Terraform Apply fails
        if: failure()
        run: exit 1