name: Terraform merge dev

on:
  push:
    branches:
      - dev

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    permissions:
      pull-requests: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
      TF_VAR_db_name: ${{ secrets.DB_NAME_DEV }}
      TF_VAR_allocated_storage: ${{ vars.ALLOCATED_STORAGE_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            terraform.tfstate.d
          key: ${{ runner.os }}-terraform-dev-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-dev-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false