name: Terraform CI/CD

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Determine Environment
        run: echo "environment=${{ github.ref == 'refs/heads/main' && 'main' || 'dev' }}" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -out=plain
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
          TF_VAR_environment: ${{ env.environment }}
        if: github.event_name == 'pull_request'

      - name: Terraform Apply Dev
        run: terraform apply -auto-approve plain
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_DEV }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
          TF_VAR_environment: dev
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

      - name: Terraform Apply Prod
        run: terraform apply -auto-approve plain
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
          TF_VAR_environment: main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'